#!/usr/bin/env node
const { exec } = require('node:child_process');
const path = require('node:path');

const startBackend = () => {
    exec('dotnet run --watch', { cwd: path.join(process.cwd(), 'API') }, (err, stdout, stderr) => {
        if (err) {
            console.error({ err, stdout, stderr });
        }
    }).stdout.on('data', (data) => {
        console.log('\x1b[36m%s\x1b', data);
    });
};

const startFrontend = () => {
    exec('yarn dev', { cwd: path.join(process.cwd(), 'web-app') }, (err, stdout, stderr) => {
        if (err) {
            console.error({ err, stdout, stderr });
        }
    }).stdout.on('data', (data) => {
        console.log(data);
    });
};

(() => {
    const mode = process.argv.slice(2)[0];

    if (mode === 'be' || mode === 'all') {
        startBackend();
    }

    if (mode === 'fe' || mode === 'all') {
        startFrontend();
    }
})();
